-- MySQL Workbench Synchronization
-- Generated: 2020-06-08 06:20
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Ayush Shashank

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `yourcloud` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `yourcloud`.`files` (
  `email` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `link` VARCHAR(2048) NOT NULL,
  CONSTRAINT `fk_mail`
    FOREIGN KEY (`email`)
    REFERENCES `yourcloud`.`user` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `yourcloud`.`user` (
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Plan` VARCHAR(45) NULL DEFAULT NULL,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
